### ISSUE TITLE
Mod browser

### ISSUE THREAD

**Issue by AnakinSkywalker066** [MaliciousFiles/EditPlayerData#1]
Btw letting you know this won’t be accepted to the mod helper browser cause it is a cheat mod

**Comment by MaliciousFiles** [comment]
No problem, I expected that! I'm curious how you found it though, I purposefully didn't give it the btd6-mod tag so I wouldn't waste your guys' time reviewing it.

**Comment by AnakinSkywalker066** [comment]
I follow u lmao

**Comment by MaliciousFiles** [comment]
Hah, well I appreciate the warning.

**Comment by AnakinSkywalker066** [comment]
Yw I just didn’t want people to get banned for stuff so they can use it
