### ISSUE TITLE
not working :/

### ISSUE THREAD

**Issue by mbcskm** [MaliciousFiles/EditPlayerData#10]
![20240316061221_1](https://github.com/MaliciousFiles/EditPlayerData/assets/80125966/8c4c248d-2984-449f-a050-d881546262d6)
not working for some reason, i installed the mod helper so tell me if thers an uncompatible mod 
![image](https://github.com/MaliciousFiles/EditPlayerData/assets/80125966/48b7c37e-235b-4e5a-af3b-f909d2e9f19e)

**Comment by MaliciousFiles** [comment]
I don't see anything incompatible. Try the new version when it comes out in a day or two. If that still doesn't work, feel free to open another issue.

If you do, make sure to send a copy of your MelonLoader console for debugging.
