### ISSUE TITLE
maps, tower xp, and powers tab not working

### ISSUE THREAD

**Issue by Jwijaya2211** [MaliciousFiles/EditPlayerData#11]
![image](https://github.com/MaliciousFiles/EditPlayerData/assets/69617706/54f9b901-4a7c-4098-91ee-b38a3acc1aa6)
![image](https://github.com/MaliciousFiles/EditPlayerData/assets/69617706/947b38ee-bbb4-49b4-a71d-03749838070a)
![image](https://github.com/MaliciousFiles/EditPlayerData/assets/69617706/9a17bc29-778e-4ccf-93ad-9ff2e790bb4f)

those 3 tabs don't work, in on v42.0.7250 
everything else fine

**Comment by DontaeGamez** [comment]
I thought it was just me

**Comment by hdjdb** [comment]
same issue. even in its previously broken tower XP state, it was a pretty useful plugin. now it is not so useful

**Comment by MaliciousFiles** [comment]
It would appear the most recent update broke it. Let me see if it's a quick fix.

**Comment by MaliciousFiles** [comment]
Working on it right now-- should be fixed within a day. Check back in a day or two, and if the new release is still bugged, feel free to open another issue.

**Comment by MaliciousFiles** [comment]
Releasing now.
