### ISSUE TITLE
Just doesn't work (fixed it, ignore this post)

### ISSUE THREAD

**Issue by theultimatD** [MaliciousFiles/EditPlayerData#17]
SO basically, I go to the player data thingy, and all I receive is this screen. I have melon loader installed fine, mod helper installed, and just this mod and mod helper currently on. I haven't installed any other mods in the past. I assume this is the best place to ask for help. Thank you.
![Screenshot 2024-10-05 223500](https://github.com/user-attachments/assets/50927fa2-64ba-4092-ba7e-141218542e82)

**Comment by MaliciousFiles** [comment]
That's uh... weird. It'd be great if you could post your MelonLoader logs. Just to confirm, from the home screen you went to settings in the top left (the gear icon), then the smaller gear icon in the bottom middle?

**Comment by theultimatD** [comment]
> That's uh... weird. It'd be great if you could post your MelonLoader logs. Just to confirm, from the home screen you went to settings in the top left (the gear icon), then the smaller gear icon in the bottom middle?

yeppers, did that. ill send my melon loader log, because i dont really know how all of this stuff works completely.
[Latest.log](https://github.com/user-attachments/files/17271171/Latest.log)
here ya go.

**Comment by MaliciousFiles** [comment]
Weird. I don't see anything wrong in the logs. Frankly my best advice without being able to reproduce myself is to try reinstalling BTD and see if it works off a clean install (assuming you sync your data to an NK account).

**Comment by theultimatD** [comment]
Hi! Sorry to ask, but does this thing I saw at the end of the log have to maybe do with anything?
"[18:56:54.580] [Il2CppInterop] Method Void SetNumColumns(Int32, Int32[]) on type EditPlayerData.UI.ModHelperTable has unsupported parameter Int32[] colFlex of type System.Int32[]
[18:56:54.634] [Il2CppInterop] Method Void SetSetting(EditPlayerData.UI.PlayerDataSetting) on type EditPlayerData.UI.PlayerDataSettingDisplay has unsupported parameter EditPlayerData.UI.PlayerDataSetting setting of type EditPlayerData.UI.PlayerDataSetting"

It sounds like something bad? I found it at the end of the log I sent and every time I tried that seemed to pop up at the end.
Ignore this if I'm wrong, I don't know anything about coding.

**Comment by MaliciousFiles** [comment]
You're good! It definitely looks bad, but it's not actually a problem. Just a weird quirk of the code I never quite figured out, shouldn't mean anything.

**Comment by theultimatD** [comment]
> You're good! Ik it looks bad, but it's not actually a problem. Just a weird quirk of the code I never quite figured out, shouldn't mean anything.

oh alr! anyways have a good day, i couldnt find any way to make it work but im sure there will be some new version or something one day so ill just be patient, anyways byeeeee :)

**Comment by MaliciousFiles** [comment]
Glad to see you fixed it! What was the issue?
