### ISSUE TITLE
Player Data Screen Completely Empty?

### ISSUE THREAD

**Issue by DodecaDonk** [MaliciousFiles/EditPlayerData#18]
Here's a picture of what it looks like. I'd assume it's similar to the problem the other issue was having. 

![image](https://github.com/user-attachments/assets/47b9e581-a2b6-4916-a493-1affa110bc2d)

**Comment by DodecaDonk** [comment]
Here's a copy of the logs: 
[Latest.log](https://github.com/user-attachments/files/17303528/Latest.log)

**Comment by krysta-saff** [comment]
It is most likely because of a major update a couple of days ago, with update 45 coming out. It likely just needs to be updated, I'd give them a few days/weeks to get it handled.

**Comment by MaliciousFiles** [comment]
This is a little different from the other issue, but @krysta-saff is correct- it's probably due to the update. I just got the email that the ModHelper sent out their update, so I'll try and get mine out this weekend (hopefully). BTW, this new update *requires* MelonLoader v0.6.5

**Comment by DodecaDonk** [comment]
I see! Thank you guys for the fast replies.

**Comment by spaff1337** [comment]
If anyone wants i updated the mod and added the fast track unlock: https://www.mediafire.com/file/k6kiskd4ozj6i73/UnlockerMod.dll/file

**Comment by MaliciousFiles** [comment]
Could you provide source code to back that up? I generally advise against downloading random DLL files. Also, if you make a pull request, I could merge it and distribute an official update.

**Comment by MaliciousFiles** [comment]
Hello all! It is officially fixed in the latest release, [v1.3.4](https://github.com/MaliciousFiles/EditPlayerData/releases/tag/v1.3.4) (including adding Fast Track). Enjoy!
