### ISSUE TITLE
[TODO] have to scroll to see Instas option

### ISSUE THREAD

**Issue by RVG-Revenge** [MaliciousFiles/EditPlayerData#23]
i downloaded the new version of the file (1.3.4) and i still cant see an option to edit how many instas u have.. everything else is there tho.. general.. tower xp.. maps.. powers.. its all there but i just cant see an instas option

any help would be appreciated

**Comment by MaliciousFiles** [comment]
Have you tried scrolling in the dropdown?

**Comment by RVG-Revenge** [comment]
can you show me a picture or something plz? i dont actually know what that means lol

**Comment by MaliciousFiles** [comment]
Yeahhh it's the only option that you have to scroll for and I really should just figure out how to make it display them all at once .-.

I'll leave this issue open so I'll hopefully remember next time I'm updating it.

**Comment by RVG-Revenge** [comment]
lmao nice one
