### ISSUE TITLE
[TODO] banner/pet/avatar sections?

### ISSUE THREAD

**Issue by RVG-Revenge** [MaliciousFiles/EditPlayerData#24]
i dont wanna ask for too much but is it possible if u can somehow make it possible to purchase packs in the shop for free? kinda like how u did double cash and fast track or just however u wanna do it.. the main thing i wanna be able to get is the pets fan pack.. i just rlly like the banner lol

again if this is too much to ask for, just say so.. i won't have my hopes too high and ill try not to have high expectations.. its fine if u aren't able to do it

**Comment by MaliciousFiles** [comment]
Not looking at the game myself, I'm not entirely sure, but could you just give yourself a bunch of trophies, then buy the banner from the trophy store? I could also maybe add another section for banners/pets, but that likely wouldn't be very soon.

**Comment by RVG-Revenge** [comment]
this banner isnt in the trophy store.. i have all the other pets but u can only get this banner from buying it with real money.. is it possible for u to make every purchase free instead of costing money? if not tho its actually ok.. dont feel like u have to do it just because 1 person brought it up

**Comment by MaliciousFiles** [comment]
Well I'll mark it as a TODO for now, I may or may not end up implementing it though.

**Comment by RVG-Revenge** [comment]
thx.. is it physically possible tho? like are u able to do it? or is it something thats pretty much impossible to do

**Comment by MaliciousFiles** [comment]
Can't say for sure without looking at the code, but it is very likely possible.

**Comment by MaliciousFiles** [comment]
Hello! Trophy store items have officially been added. Unfortunately I can't do packs (the purchases get a little complicated beyond Fast Track and Double Cash), but all other items should be easily unlockable now! Check out the (latest release)[https://github.com/MaliciousFiles/EditPlayerData/releases/latest].

**Comment by RVG-Revenge** [comment]
hi
thanks so much
is it possible to get at least the avatar and banners in the packs tho? the rest dont matter.. the avatar and banner is the main thing.. mostly just the pet avatar and banner

**Comment by MaliciousFiles** [comment]
Unfortunately, as mentioned above, purchases get very complicated. Reverse engineering that whole API would be rather difficult. However, any banners/pets/avatars that are in the trophy store can now be unlocked by the mod.

I'm sorry, but I cannot easily provide pack unlocks.

**Comment by RVG-Revenge** [comment]
its ok dont worry about it.. everything u have done is way more than enough and we all cant thank u enough.. we appreciate u so much!!

**Comment by RVG-Revenge** [comment]
bro...... 
omg
bro u actually already did it without realising.. the pet banner and all the other banners and avatars that cost real money have been unlocked.. it was in the trophy store items part.. i was scrolling through everything i could unlock and i saw it all there!! u actually did it lmaoo no wayyyyy
![image](https://github.com/user-attachments/assets/73efc232-f456-4ec4-88c7-e1795dcd25a0)
![image](https://github.com/user-attachments/assets/449043cb-f667-4ec8-ab84-18afd2147792)

**Comment by MaliciousFiles** [comment]
Well there you go! Glad it works. :)
