### ISSUE TITLE
[TODO] trophy store items

### ISSUE THREAD

**Issue by klndwl** [MaliciousFiles/EditPlayerData#28]
i can use everything without getting flagged except for adding trophies, could an "unlock trophy items" feature be added to give your account all of these items? i dont think it would flag since the old mod that did that never flagged

**Comment by MaliciousFiles** [comment]
Yeah, I'll look into it whenever I get around to #24. Good to know that adding trophies gets you flagged.

Hopefully I'll have time relatively soon, but will probably be a few weeks.

**Comment by MaliciousFiles** [comment]
Implemented in 7a4f282
