### ISSUE TITLE
can you please add a feature for un flagging an account or making it unflaggable? pleaseee

### ISSUE THREAD

**Issue by 632763276327ermwhatthesigma** [MaliciousFiles/EditPlayerData#29]
i cant use alot of features because my account is flagged obviously since im using mods but you know can you just please try?

**Comment by MaliciousFiles** [comment]
Unfortunately, even if I could figure out how, I don't think it would be moral to release such an update. That said, most of the features of this mod usually do not flag you unless they are used for online play. **I always recommend using an alternate account for modded play.**

However, if your main account did get banned, you can always create another, and then use this mod to get it back up to the same level and unlocks.

**Comment by 632763276327ermwhatthesigma** [comment]
Alright, thanks though.

**Comment by 632763276327ermwhatthesigma** [comment]
1 more thing if you could please think it through I keep getting flagged whenever i make a new account and now both of my accounts on the cloud have been deleted but they're still all getting flagged. If you could just think this through 1 more time it would mean alot to me because my account of multiple years is the one thats flagged, please and thank you. If not thats ok.

**Comment by MaliciousFiles** [comment]
Frankly, I'm not sure whether it's possible. It would take some looking into. I'll take a look next time I'm updating this project, but no promises as to when that'll be. That said, I'm pretty sure you should be able to make a fresh account and give yourself all the towers, monkey knowledge, etc. without getting flagged.

**Comment by 632763276327ermwhatthesigma** [comment]
I've tried that it just auto flags it the only way I can get it to not flag immediatly is to do data swaps then do it but after i leave the game and reopen it its flagged.

**Comment by MaliciousFiles** [comment]
What exactly are you setting your player data values to? I can try to reproduce on my end.

**Comment by MaliciousFiles** [comment]
Were you only setting player XP? If you can tell me all the various settings your were changing, I can try it and see if I get flagged.
