### ISSUE TITLE
How can i change other things?

### ISSUE THREAD

**Issue by TheFinality** [MaliciousFiles/EditPlayerData#3]
Really new to this, but I was wondering how I could add on to this project. I see that you use GetPlayer().Data. a lot to change stuff, and I wanna know how you are getting all the names of stuff you can change. Like in this line: () => GetPlayer().Data.monkeyMoney.ValueInt, t => GetPlayer().Data.monkeyMoney.Value = t), where did you get monkeyMoney from? I went through btd6 mod helper but couldn't find anything.

**Comment by MaliciousFiles** [comment]
Unfortunately, none of this is officially sanctioned, so I couldn't use the mod helper. I found these names directly from the source code, through my IDE. It basically just gave me some tab complete options and that I looked through for things I wanted to change. I would recommend JetBrains' Rider (free if you're enrolled in public education), or VS.

**Comment by TheFinality** [comment]
Which source code are you looking through? I’ve looked thru btd6 mod helper’s source, but haven’t found anything yet

**Comment by MaliciousFiles** [comment]
The BTD6 source code directly.

**Comment by MaliciousFiles** [comment]
Apologies, I do use ModHelper, but only for the UI. Not for any of the editing data. Should be fixed in v1.3.1 though!
