### ISSUE TITLE
[TODO] add multiple instas at a time

### ISSUE THREAD

**Issue by Artwav3** [MaliciousFiles/EditPlayerData#30]
is there anyway you can add back the images to the keybinds i believe you had like F1, F2, F3 etc to be able to enable giving like 50 instas per click and do different things but the picture along with the comments were removed

**Comment by MaliciousFiles** [comment]
I don't believe I did ever have that, you must be thinking of a different mod. A button to do that is a good idea, however.

**Comment by Artwav3** [comment]
it was indeed a different mod for btd6 but yes if key binds can be added that would be great also wanted to know if theres anyway to add co-op badges to the mod so we can edit safe file as well as a edit tool to monkeys used to show acct being more legit lol

**Comment by MaliciousFiles** [comment]
I'm a little confused. Is the second part just asking to being able to manipulate co-op medals?

**Comment by Artwav3** [comment]
yes asking if badges can be changed  to get the badges from coop maps not just unlocking the regular ones 
![image](https://github.com/user-attachments/assets/6818613a-dc8d-43ec-927c-c262771e5477)

**Comment by MaliciousFiles** [comment]
Ah. I'll consider it for the next update.

**Comment by MaliciousFiles** [comment]
The multiple instas thing already exists; you can add an arbitrary number of every insta, or set the value of a particular insta. This should accomplish whatever you desire.
