### ISSUE TITLE
[TODO] more Tower XP input characters

### ISSUE THREAD

**Issue by KNIZE1007** [MaliciousFiles/EditPlayerData#32]
When you set the tower XP, you cannot set it above 7 digits, could that be changed to at least 8 digits? 

(as to why i am asking, i am using this mod to "transfer" my progress from btd6 netflix to btd6 on pc, and a lot of my towers have xp above 10 mil, and i cant set it to the right amounts)

**Comment by MaliciousFiles** [comment]
Holy cow, that's a lot of XP. Yeah, that shouldn't be too hard, I'll do it in the next update (which I'm thinking may be this weekend, but no guarantees).

P.S. glad to see the mod in use for a legit purpose! :D

**Comment by Spirant123** [comment]
Hey, not sure if it is just me but this mod no longer works.

**Comment by MaliciousFiles** [comment]
Please open a new issue through [https://github.com/MaliciousFiles/EditPlayerData/issues/new](https://github.com/MaliciousFiles/EditPlayerData/issues/new). When you do, include a screenshot of the MelonLoader logs, or a crash report.
