### ISSUE TITLE
[TODO] multiplayer badges and tower placed stats

### ISSUE THREAD

**Issue by Spirant123** [MaliciousFiles/EditPlayerData#38]
Honestly not sure how any of this works, but you have done a good job and if this was possible it would be cool to see.

**Comment by Spirant123** [comment]
also is there a way to edit the monkey placed stat per tower
![image](https://github.com/user-attachments/assets/837a9d63-9a3f-4f38-92e5-a825959083c1)

**Comment by RVG-Revenge** [comment]
ahhh i wish

**Comment by MaliciousFiles** [comment]
I'll take a look at these when I get around to updating it pretty soon. Thanks for the suggestion!

**Comment by MaliciousFiles** [comment]
Unfortunately, I couldn't find a way to do Tower Placed stats. You can probably just grind them in sandbox though, or use monkey money to get a bunch of cash drops and easily grind them that way. Multiplayer badges (and all other online mode things) have been added in the [latest release](https://github.com/MaliciousFiles/EditPlayerData/releases/latest), however!
