### ISSUE TITLE
Only general tab works after most recent update 

### ISSUE THREAD

**Issue by SillyLilyy** [MaliciousFiles/EditPlayerData#4]
Before the most recent update you could edit instas maps and tower xp and now it no longer works

**Comment by xalau820** [comment]
I hope the author can fix it！

**Comment by hyacinth-01** [comment]
Dear author,In the latest 40 editions, mod module has many functions that can't be used. I hope you can repair it

**Comment by MaliciousFiles** [comment]
I believe it worked in my testing, but BTD6 has updated since I last worked on this project. Could you give me a little more information on what isn't working? Maybe a console log or screenshot?

**Comment by xalau820** [comment]
![01](https://github.com/MaliciousFiles/EditPlayerData/assets/153145028/28902b17-5c23-4894-8bc3-eddc4bb8c635)
Maps,Tower XP,Powers,Instas are not working anymore。

**Comment by hyacinth-01** [comment]
![Cache_72ff3c2d991d9f52](https://github.com/MaliciousFiles/EditPlayerData/assets/142307078/ff284896-faac-466b-8ca9-16d68a5fa834)
![Cache_-5b4a608d291a805b](https://github.com/MaliciousFiles/EditPlayerData/assets/142307078/45c8d5bd-a0b5-4f3a-a3dc-024364e56ebc)
![Cache_-3bdb2e32309436a1](https://github.com/MaliciousFiles/EditPlayerData/assets/142307078/d9273c59-9ec2-4c5a-9d7c-f92f54ce58fb)
![Cache_2a744d2b57dec786](https://github.com/MaliciousFiles/EditPlayerData/assets/142307078/68333e13-117a-4c60-bede-b7a0349a91cf)
Dear author, update the mod module if you are free.

**Comment by MaliciousFiles** [comment]
Looks like NK reworked their backend. I'm currently in the middle of finals for school, but I'll look into updating it in the coming weeks.

**Comment by SLH879** [comment]
Thanks for recognizing this issue and willing to update. Happy holidays and good luck on your finals

**Comment by MaliciousFiles** [comment]
Should be fixed in v1.3.1! Let me know if you have any further issues.

**Comment by SLH879** [comment]
YOu're amazing. Thank you!

**Comment by hyacinth-01** [comment]
Thank you very much for your efforts and have a happy life

**Comment by SirBlueAxolotl** [comment]
It's still broken :C

**Comment by SLH879** [comment]
It's fixed. have tested it on different PCs. Be sure to get the latest modhelper, bc the outdated modhelper was what broke this mod originally for me.
