### ISSUE TITLE
[TODO] boss/race/contested territory medals?

### ISSUE THREAD

**Issue by RVG-Revenge** [MaliciousFiles/EditPlayerData#40]
plz can u make it possible to edit other medals such as bosses and races and contested territory and stuff

**Comment by MaliciousFiles** [comment]
I may, though I have to ask: why do you want to be able to edit them? I mostly ask because I don't want this mod to simply be a way to cheat, but have some practical purpose.

**Comment by RVG-Revenge** [comment]
its because i got my main account flagged but luckily i managed to get NK to remove it.. but the reason i want this is because just in case this happens again, i can make an exact replica of my main account instead of grinding for all boss medals and oddessy stars again for months

**Comment by MaliciousFiles** [comment]
Done! Check out the [latest release](https://github.com/MaliciousFiles/EditPlayerData/releases/latest).
