### ISSUE TITLE
Social play (quick play) dosnt work

### ISSUE THREAD

**Issue by Kempo123** [MaliciousFiles/EditPlayerData#43]
Matches with other people dosnt work
- no people show for matches

**Comment by MaliciousFiles** [comment]
What do you mean no people show? Like you cannot play coop games?

If so, that may be a result of being flagged. Does your game have two exit buttons?

**Comment by Kempo123** [comment]
There is no mark of being flagged (no leaf under profile pic) 

When i go to co-up and try to launch a game then no people show up for the matches.

**Comment by Kempo123** [comment]
I got an option to press public in the co-up match menu and after a pop-up says:

Disconnected
Game values cannot be resynced. Unfortunately this game cannot continue. Please try a new game.

- I do not know what to do

**Comment by Kempo123** [comment]
When i hower over the public button in co-up (these game settings can only  be played as a Private match)

**Comment by Kempo123** [comment]
I dont know if i was a bug. Now it seems to work fine

**Comment by MaliciousFiles** [comment]
Sounds good! Glad it's working.

**Comment by Kempo123** [comment]
![Uploading bloon1.PNG…]()

**Comment by Kempo123** [comment]
![Uploading bloon 2.PNG…]()

**Comment by Kempo123** [comment]
encountered a new problem with co-up. I seems like a could play a game or two, and then i encountered this - I'm still not flagged
