### ISSUE TITLE
is there a way to edit tower xp

### ISSUE THREAD

**Issue by sunspeedd** [MaliciousFiles/EditPlayerData#9]
is there a way to edit tower xp? there is a tower tab but it only shows the dartmonkey, i dont know what its supposed to do or what the edit button for that is for

**Comment by MaliciousFiles** [comment]
Hello! Unfortunately it is currently broken, as NK changed up their backend a little. I'm working on a fix, but frankly I've got a lot going on, so it may be a little. Thank you for your patience!

**Comment by MaliciousFiles** [comment]
Should be fixed within a couple days!
